#!/bin/sh /etc/rc.common

START=99
STOP=85
USE_PROCD=1
WISED=/usr/bin/kios

start_service() {
	procd_open_instance
	procd_set_param command $WISED
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-10}
#	procd_set_param stdout 1 # forward stdout of the command to logd
# 	procd_set_param stderr 1 # same for stderr
	procd_close_instance
}

stop() {
	echo "Stopping the kios service"
}
#service_triggers()
#{
#	procd_add_reload_trigger "dhcp"
#}

